[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:daphne]
command=daphne -b 127.0.0.1 -p 8000 niba_mart_project.asgi:application
directory=/niba_mart_project   ; ← was /app
priority=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
priority=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0